### ISSUE TITLE
Arkdata without database

### ISSUE THREAD

**Issue by timhuijgen** [knightzac19/NodeJS-ArkData#2]
Hi, I've made a new nodejs package where it just gets the profile & tribe data and formats it, returns the data directly and caches it in memory. I've some of your code, especially the formatting part. Do you mind if I publish it, of course with credits to you.

**Comment by knightzac19** [comment]
This is fine, but just a heads up, this project will be getting superseded by a much bigger project I've converted over from C#. It'll have a lot more power to parse all the ark files.

**Comment by timhuijgen** [comment]
Awesome, I'm looking forward to it.
